name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        shell: bash
        run: |
          yarn --immutable

      - name: Build and validate packages
        run: |
          yarn workspaces foreach -t run build

      - name: Run all tests
        run: |
          yarn test
